-- MySQL Script generated by MySQL Workbench
-- Fri Mar 17 18:09:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hw25
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hw25
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hw25` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hw25` ;

-- -----------------------------------------------------
-- Table `hw25`.`homework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hw25`.`homework` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hw25`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hw25`.`lesson` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `homework_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `homework_id_idx` (`homework_id` ASC) VISIBLE,
  CONSTRAINT `homework_id`
    FOREIGN KEY (`homework_id`)
    REFERENCES `hw25`.`homework` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hw25`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hw25`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lessons` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `hw25`.`schedules_lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hw25`.`schedules_lessons` (
  `schedule_id` INT NOT NULL,
  `lesson_id` INT NOT NULL,
  INDEX `les_id_idx` (`lesson_id` ASC) VISIBLE,
  INDEX `sched_id_idx` (`schedule_id` ASC) VISIBLE,
  CONSTRAINT `lesson_id`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `hw25`.`lesson` (`id`),
  CONSTRAINT `schedule_id`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `hw25`.`schedule` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
